# frozen_string_literal: true

RSpec.shared_context 'yahoo_roster_response_stubs' do
  let(:roster) do
    "<coverage_type>date</coverage_type>
    <date>2019-03-29</date>
    <is_editable>1</is_editable>
    <players count=\"23\">
      <player>
        <player_key>388.p.10959</player_key>
        <player_id>10959</player_id>
        <name>
          <full>Danny Jansen</full>
          <first>Danny</first>
          <last>Jansen</last>
          <ascii_first>Danny</ascii_first>
          <ascii_last>Jansen</ascii_last>
        </name>
        <editorial_player_key>mlb.p.10959</editorial_player_key>
        <editorial_team_key>mlb.t.14</editorial_team_key>
        <editorial_team_full_name>Toronto Blue Jays</editorial_team_full_name>
        <editorial_team_abbr>Tor</editorial_team_abbr>
        <uniform_number>9</uniform_number>
        <display_position>C</display_position>
        <headshot>
          <url>https://s.yimg.com/iu/api/res/1.2/L5A6q.QJCvDKNPW84vy5YA--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03122018/10959.png</url>
          <size>small</size>
        </headshot>
        <image_url>https://s.yimg.com/iu/api/res/1.2/L5A6q.QJCvDKNPW84vy5YA--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03122018/10959.png</image_url>
        <is_undroppable>0</is_undroppable>
        <position_type>B</position_type>
        <eligible_positions>
          <position>C</position>
          <position>Util</position>
        </eligible_positions>
        <selected_position>
          <coverage_type>date</coverage_type>
          <date>2019-03-29</date>
          <position>C</position>
        </selected_position>
        <is_editable>1</is_editable>
      </player>
      <player>
        <player_key>388.p.8868</player_key>
        <player_id>8868</player_id>
        <name>
          <full>Anthony Rizzo</full>
          <first>Anthony</first>
          <last>Rizzo</last>
          <ascii_first>Anthony</ascii_first>
          <ascii_last>Rizzo</ascii_last>
        </name>
        <editorial_player_key>mlb.p.8868</editorial_player_key>
        <editorial_team_key>mlb.t.16</editorial_team_key>
        <editorial_team_full_name>Chicago Cubs</editorial_team_full_name>
        <editorial_team_abbr>ChC</editorial_team_abbr>
        <uniform_number>44</uniform_number>
        <display_position>1B</display_position>
        <headshot>
          <url>https://s.yimg.com/iu/api/res/1.2/Ft5Lg8UtnTpx1_SrwWdoyw--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03192018/8868.png</url>
          <size>small</size>
        </headshot>
        <image_url>https://s.yimg.com/iu/api/res/1.2/Ft5Lg8UtnTpx1_SrwWdoyw--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03192018/8868.png</image_url>
        <is_undroppable>0</is_undroppable>
        <position_type>B</position_type>
        <eligible_positions>
          <position>1B</position>
          <position>Util</position>
        </eligible_positions>
        <selected_position>
          <coverage_type>date</coverage_type>
          <date>2019-03-29</date>
          <position>1B</position>
        </selected_position>
        <is_editable>1</is_editable>
      </player>
      <player>
        <player_key>388.p.9104</player_key>
        <player_id>9104</player_id>
        <name>
          <full>Jonathan Schoop</full>
          <first>Jonathan</first>
          <last>Schoop</last>
          <ascii_first>Jonathan</ascii_first>
          <ascii_last>Schoop</ascii_last>
        </name>
        <status>DTD</status>
        <status_full>Day-to-Day</status_full>
        <editorial_player_key>mlb.p.9104</editorial_player_key>
        <editorial_team_key>mlb.t.9</editorial_team_key>
        <editorial_team_full_name>Minnesota Twins</editorial_team_full_name>
        <editorial_team_abbr>Min</editorial_team_abbr>
        <uniform_number>16</uniform_number>
        <display_position>2B,SS</display_position>
        <headshot>
          <url>https://s.yimg.com/iu/api/res/1.2/PDva63V8oejaLgLVOaOghw--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03222019/9104.1.png</url>
          <size>small</size>
        </headshot>
        <image_url>https://s.yimg.com/iu/api/res/1.2/PDva63V8oejaLgLVOaOghw--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03222019/9104.1.png</image_url>
        <is_undroppable>0</is_undroppable>
        <position_type>B</position_type>
        <eligible_positions>
          <position>2B</position>
          <position>SS</position>
          <position>Util</position>
        </eligible_positions>
        <has_player_notes>1</has_player_notes>
        <player_notes_last_timestamp>1553390280</player_notes_last_timestamp>
        <selected_position>
          <coverage_type>date</coverage_type>
          <date>2019-03-29</date>
          <position>2B</position>
        </selected_position>
        <is_editable>1</is_editable>
      </player>
      <player>
        <player_key>388.p.10235</player_key>
        <player_id>10235</player_id>
        <name>
          <full>Rafael Devers</full>
          <first>Rafael</first>
          <last>Devers</last>
          <ascii_first>Rafael</ascii_first>
          <ascii_last>Devers</ascii_last>
        </name>
        <editorial_player_key>mlb.p.10235</editorial_player_key>
        <editorial_team_key>mlb.t.2</editorial_team_key>
        <editorial_team_full_name>Boston Red Sox</editorial_team_full_name>
        <editorial_team_abbr>Bos</editorial_team_abbr>
        <uniform_number>11</uniform_number>
        <display_position>3B</display_position>
        <headshot>
          <url>https://s.yimg.com/iu/api/res/1.2/25TBldoQoKaIo7ay_CS7iA--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03072018/10235.png</url>
          <size>small</size>
        </headshot>
        <image_url>https://s.yimg.com/iu/api/res/1.2/25TBldoQoKaIo7ay_CS7iA--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03072018/10235.png</image_url>
        <is_undroppable>0</is_undroppable>
        <position_type>B</position_type>
        <eligible_positions>
          <position>3B</position>
          <position>Util</position>
        </eligible_positions>
        <has_player_notes>1</has_player_notes>
        <player_notes_last_timestamp>1553724900</player_notes_last_timestamp>
        <selected_position>
          <coverage_type>date</coverage_type>
          <date>2019-03-29</date>
          <position>3B</position>
        </selected_position>
        <is_editable>1</is_editable>
      </player>
      <player>
        <player_key>388.p.9897</player_key>
        <player_id>9897</player_id>
        <name>
          <full>Tim Anderson</full>
          <first>Tim</first>
          <last>Anderson</last>
          <ascii_first>Tim</ascii_first>
          <ascii_last>Anderson</ascii_last>
        </name>
        <editorial_player_key>mlb.p.9897</editorial_player_key>
        <editorial_team_key>mlb.t.4</editorial_team_key>
        <editorial_team_full_name>Chicago White Sox</editorial_team_full_name>
        <editorial_team_abbr>CWS</editorial_team_abbr>
        <uniform_number>7</uniform_number>
        <display_position>SS</display_position>
        <headshot>
          <url>https://s.yimg.com/iu/api/res/1.2/L.j3ECJjtDqPF5VTwINo1A--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/04032018/9897.png</url>
          <size>small</size>
        </headshot>
        <image_url>https://s.yimg.com/iu/api/res/1.2/L.j3ECJjtDqPF5VTwINo1A--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/04032018/9897.png</image_url>
        <is_undroppable>0</is_undroppable>
        <position_type>B</position_type>
        <eligible_positions>
          <position>SS</position>
          <position>Util</position>
        </eligible_positions>
        <selected_position>
          <coverage_type>date</coverage_type>
          <date>2019-03-29</date>
          <position>SS</position>
        </selected_position>
        <is_editable>1</is_editable>
      </player>
      <player>
        <player_key>388.p.9320</player_key>
        <player_id>9320</player_id>
        <name>
          <full>Christian Yelich</full>
          <first>Christian</first>
          <last>Yelich</last>
          <ascii_first>Christian</ascii_first>
          <ascii_last>Yelich</ascii_last>
        </name>
        <editorial_player_key>mlb.p.9320</editorial_player_key>
        <editorial_team_key>mlb.t.8</editorial_team_key>
        <editorial_team_full_name>Milwaukee Brewers</editorial_team_full_name>
        <editorial_team_abbr>Mil</editorial_team_abbr>
        <uniform_number>22</uniform_number>
        <display_position>OF</display_position>
        <headshot>
          <url>https://s.yimg.com/iu/api/res/1.2/R_nK_1tauFS2U5Z2W7mYeQ--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03082018/9320.png</url>
          <size>small</size>
        </headshot>
        <image_url>https://s.yimg.com/iu/api/res/1.2/R_nK_1tauFS2U5Z2W7mYeQ--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03082018/9320.png</image_url>
        <is_undroppable>1</is_undroppable>
        <position_type>B</position_type>
        <eligible_positions>
          <position>OF</position>
          <position>Util</position>
        </eligible_positions>
        <has_player_notes>1</has_player_notes>
        <has_recent_player_notes>1</has_recent_player_notes>
        <player_notes_last_timestamp>1553806800</player_notes_last_timestamp>
        <selected_position>
          <coverage_type>date</coverage_type>
          <date>2019-03-29</date>
          <position>OF</position>
        </selected_position>
        <is_editable>1</is_editable>
      </player>
      <player>
        <player_key>388.p.10626</player_key>
        <player_id>10626</player_id>
        <name>
          <full>Juan Soto</full>
          <first>Juan</first>
          <last>Soto</last>
          <ascii_first>Juan</ascii_first>
          <ascii_last>Soto</ascii_last>
        </name>
        <editorial_player_key>mlb.p.10626</editorial_player_key>
        <editorial_team_key>mlb.t.20</editorial_team_key>
        <editorial_team_full_name>Washington Nationals</editorial_team_full_name>
        <editorial_team_abbr>Was</editorial_team_abbr>
        <uniform_number>22</uniform_number>
        <display_position>OF</display_position>
        <headshot>
          <url>https://s.yimg.com/iu/api/res/1.2/iu4prpsZprawaCM2la52_A--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/09182018/10626.1.png</url>
          <size>small</size>
        </headshot>
        <image_url>https://s.yimg.com/iu/api/res/1.2/iu4prpsZprawaCM2la52_A--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/09182018/10626.1.png</image_url>
        <is_undroppable>0</is_undroppable>
        <position_type>B</position_type>
        <eligible_positions>
          <position>OF</position>
          <position>Util</position>
        </eligible_positions>
        <selected_position>
          <coverage_type>date</coverage_type>
          <date>2019-03-29</date>
          <position>OF</position>
        </selected_position>
        <is_editable>1</is_editable>
      </player>
      <player>
        <player_key>388.p.9385</player_key>
        <player_id>9385</player_id>
        <name>
          <full>Marcell Ozuna</full>
          <first>Marcell</first>
          <last>Ozuna</last>
          <ascii_first>Marcell</ascii_first>
          <ascii_last>Ozuna</ascii_last>
        </name>
        <editorial_player_key>mlb.p.9385</editorial_player_key>
        <editorial_team_key>mlb.t.24</editorial_team_key>
        <editorial_team_full_name>St. Louis Cardinals</editorial_team_full_name>
        <editorial_team_abbr>StL</editorial_team_abbr>
        <uniform_number>23</uniform_number>
        <display_position>OF</display_position>
        <headshot>
          <url>https://s.yimg.com/iu/api/res/1.2/iKK3PMI4825XllG_KcEe1g--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03092018/9385.png</url>
          <size>small</size>
        </headshot>
        <image_url>https://s.yimg.com/iu/api/res/1.2/iKK3PMI4825XllG_KcEe1g--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03092018/9385.png</image_url>
        <is_undroppable>0</is_undroppable>
        <position_type>B</position_type>
        <eligible_positions>
          <position>OF</position>
          <position>Util</position>
        </eligible_positions>
        <has_player_notes>1</has_player_notes>
        <player_notes_last_timestamp>1553203560</player_notes_last_timestamp>
        <selected_position>
          <coverage_type>date</coverage_type>
          <date>2019-03-29</date>
          <position>OF</position>
        </selected_position>
        <is_editable>1</is_editable>
      </player>
      <player>
        <player_key>388.p.9565</player_key>
        <player_id>9565</player_id>
        <name>
          <full>David Dahl</full>
          <first>David</first>
          <last>Dahl</last>
          <ascii_first>David</ascii_first>
          <ascii_last>Dahl</ascii_last>
        </name>
        <editorial_player_key>mlb.p.9565</editorial_player_key>
        <editorial_team_key>mlb.t.27</editorial_team_key>
        <editorial_team_full_name>Colorado Rockies</editorial_team_full_name>
        <editorial_team_abbr>Col</editorial_team_abbr>
        <uniform_number>26</uniform_number>
        <display_position>OF</display_position>
        <headshot>
          <url>https://s.yimg.com/iu/api/res/1.2/QLdGBtc9IQuz6OevtaRD3w--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03212018/9565.png</url>
          <size>small</size>
        </headshot>
        <image_url>https://s.yimg.com/iu/api/res/1.2/QLdGBtc9IQuz6OevtaRD3w--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03212018/9565.png</image_url>
        <is_undroppable>0</is_undroppable>
        <position_type>B</position_type>
        <eligible_positions>
          <position>OF</position>
          <position>Util</position>
        </eligible_positions>
        <has_player_notes>1</has_player_notes>
        <has_recent_player_notes>1</has_recent_player_notes>
        <player_notes_last_timestamp>1553824500</player_notes_last_timestamp>
        <selected_position>
          <coverage_type>date</coverage_type>
          <date>2019-03-29</date>
          <position>Util</position>
        </selected_position>
        <is_editable>1</is_editable>
      </player>
      <player>
        <player_key>388.p.7977</player_key>
        <player_id>7977</player_id>
        <name>
          <full>Andrew McCutchen</full>
          <first>Andrew</first>
          <last>McCutchen</last>
          <ascii_first>Andrew</ascii_first>
          <ascii_last>McCutchen</ascii_last>
        </name>
        <editorial_player_key>mlb.p.7977</editorial_player_key>
        <editorial_team_key>mlb.t.22</editorial_team_key>
        <editorial_team_full_name>Philadelphia Phillies</editorial_team_full_name>
        <editorial_team_abbr>Phi</editorial_team_abbr>
        <uniform_number>22</uniform_number>
        <display_position>OF</display_position>
        <headshot>
          <url>https://s.yimg.com/iu/api/res/1.2/PGJ2ut3Vr1xH06_8RvvSnw--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03222019/7977.1.png</url>
          <size>small</size>
        </headshot>
        <image_url>https://s.yimg.com/iu/api/res/1.2/PGJ2ut3Vr1xH06_8RvvSnw--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03222019/7977.1.png</image_url>
        <is_undroppable>0</is_undroppable>
        <position_type>B</position_type>
        <eligible_positions>
          <position>OF</position>
          <position>Util</position>
        </eligible_positions>
        <has_player_notes>1</has_player_notes>
        <has_recent_player_notes>1</has_recent_player_notes>
        <player_notes_last_timestamp>1553811360</player_notes_last_timestamp>
        <selected_position>
          <coverage_type>date</coverage_type>
          <date>2019-03-29</date>
          <position>Util</position>
        </selected_position>
        <is_editable>1</is_editable>
      </player>
      <player>
        <player_key>388.p.11016</player_key>
        <player_id>11016</player_id>
        <name>
          <full>Franmil Reyes</full>
          <first>Franmil</first>
          <last>Reyes</last>
          <ascii_first>Franmil</ascii_first>
          <ascii_last>Reyes</ascii_last>
        </name>
        <editorial_player_key>mlb.p.11016</editorial_player_key>
        <editorial_team_key>mlb.t.25</editorial_team_key>
        <editorial_team_full_name>San Diego Padres</editorial_team_full_name>
        <editorial_team_abbr>SD</editorial_team_abbr>
        <uniform_number>32</uniform_number>
        <display_position>OF</display_position>
        <headshot>
          <url>https://s.yimg.com/iu/api/res/1.2/QatRpPMpZCWyiZOGtb82SA--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03222019/11016.1.png</url>
          <size>small</size>
        </headshot>
        <image_url>https://s.yimg.com/iu/api/res/1.2/QatRpPMpZCWyiZOGtb82SA--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03222019/11016.1.png</image_url>
        <is_undroppable>0</is_undroppable>
        <position_type>B</position_type>
        <eligible_positions>
          <position>OF</position>
          <position>Util</position>
        </eligible_positions>
        <has_player_notes>1</has_player_notes>
        <player_notes_last_timestamp>1553386320</player_notes_last_timestamp>
        <selected_position>
          <coverage_type>date</coverage_type>
          <date>2019-03-29</date>
          <position>BN</position>
        </selected_position>
        <is_editable>1</is_editable>
      </player>
      <player>
        <player_key>388.p.9338</player_key>
        <player_id>9338</player_id>
        <name>
          <full>Jackie Bradley Jr.</full>
          <first>Jackie</first>
          <last>Bradley Jr.</last>
          <ascii_first>Jackie</ascii_first>
          <ascii_last>Bradley Jr.</ascii_last>
        </name>
        <editorial_player_key>mlb.p.9338</editorial_player_key>
        <editorial_team_key>mlb.t.2</editorial_team_key>
        <editorial_team_full_name>Boston Red Sox</editorial_team_full_name>
        <editorial_team_abbr>Bos</editorial_team_abbr>
        <uniform_number>19</uniform_number>
        <display_position>OF</display_position>
        <headshot>
          <url>https://s.yimg.com/iu/api/res/1.2/72IvRrmSEKUn2jmUuaX53g--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03142018/9338.png</url>
          <size>small</size>
        </headshot>
        <image_url>https://s.yimg.com/iu/api/res/1.2/72IvRrmSEKUn2jmUuaX53g--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03142018/9338.png</image_url>
        <is_undroppable>0</is_undroppable>
        <position_type>B</position_type>
        <eligible_positions>
          <position>OF</position>
          <position>Util</position>
        </eligible_positions>
        <has_player_notes>1</has_player_notes>
        <player_notes_last_timestamp>1553370600</player_notes_last_timestamp>
        <selected_position>
          <coverage_type>date</coverage_type>
          <date>2019-03-29</date>
          <position>BN</position>
        </selected_position>
        <is_editable>1</is_editable>
      </player>
      <player>
        <player_key>388.p.10344</player_key>
        <player_id>10344</player_id>
        <name>
          <full>Yuli Gurriel</full>
          <first>Yuli</first>
          <last>Gurriel</last>
          <ascii_first>Yuli</ascii_first>
          <ascii_last>Gurriel</ascii_last>
        </name>
        <editorial_player_key>mlb.p.10344</editorial_player_key>
        <editorial_team_key>mlb.t.18</editorial_team_key>
        <editorial_team_full_name>Houston Astros</editorial_team_full_name>
        <editorial_team_abbr>Hou</editorial_team_abbr>
        <uniform_number>10</uniform_number>
        <display_position>1B,2B,3B</display_position>
        <headshot>
          <url>https://s.yimg.com/iu/api/res/1.2/mkWQp2SYfa_Vr8a8lSslAQ--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03162018/10344.png</url>
          <size>small</size>
        </headshot>
        <image_url>https://s.yimg.com/iu/api/res/1.2/mkWQp2SYfa_Vr8a8lSslAQ--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03162018/10344.png</image_url>
        <is_undroppable>0</is_undroppable>
        <position_type>B</position_type>
        <eligible_positions>
          <position>1B</position>
          <position>2B</position>
          <position>3B</position>
          <position>Util</position>
        </eligible_positions>
        <has_player_notes>1</has_player_notes>
        <player_notes_last_timestamp>1553303940</player_notes_last_timestamp>
        <selected_position>
          <coverage_type>date</coverage_type>
          <date>2019-03-29</date>
          <position>BN</position>
        </selected_position>
        <is_editable>1</is_editable>
      </player>
      <player>
        <player_key>388.p.7914</player_key>
        <player_id>7914</player_id>
        <name>
          <full>Evan Longoria</full>
          <first>Evan</first>
          <last>Longoria</last>
          <ascii_first>Evan</ascii_first>
          <ascii_last>Longoria</ascii_last>
        </name>
        <editorial_player_key>mlb.p.7914</editorial_player_key>
        <editorial_team_key>mlb.t.26</editorial_team_key>
        <editorial_team_full_name>San Francisco Giants</editorial_team_full_name>
        <editorial_team_abbr>SF</editorial_team_abbr>
        <uniform_number>10</uniform_number>
        <display_position>3B</display_position>
        <headshot>
          <url>https://s.yimg.com/iu/api/res/1.2/AwkX5G9Z4CYywG9QzcKAVQ--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03082018/7914.png</url>
          <size>small</size>
        </headshot>
        <image_url>https://s.yimg.com/iu/api/res/1.2/AwkX5G9Z4CYywG9QzcKAVQ--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03082018/7914.png</image_url>
        <is_undroppable>0</is_undroppable>
        <position_type>B</position_type>
        <eligible_positions>
          <position>3B</position>
          <position>Util</position>
        </eligible_positions>
        <has_player_notes>1</has_player_notes>
        <has_recent_player_notes>1</has_recent_player_notes>
        <player_notes_last_timestamp>1553818800</player_notes_last_timestamp>
        <selected_position>
          <coverage_type>date</coverage_type>
          <date>2019-03-29</date>
          <position>BN</position>
        </selected_position>
        <is_editable>1</is_editable>
      </player>
      <player>
        <player_key>388.p.9771</player_key>
        <player_id>9771</player_id>
        <name>
          <full>Chris Taylor</full>
          <first>Chris</first>
          <last>Taylor</last>
          <ascii_first>Chris</ascii_first>
          <ascii_last>Taylor</ascii_last>
        </name>
        <editorial_player_key>mlb.p.9771</editorial_player_key>
        <editorial_team_key>mlb.t.19</editorial_team_key>
        <editorial_team_full_name>Los Angeles Dodgers</editorial_team_full_name>
        <editorial_team_abbr>LAD</editorial_team_abbr>
        <uniform_number>3</uniform_number>
        <display_position>2B,SS,OF</display_position>
        <headshot>
          <url>https://s.yimg.com/iu/api/res/1.2/PVfAsIXA.m9sfUrhvw9Q9g--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/04192018/9771.png</url>
          <size>small</size>
        </headshot>
        <image_url>https://s.yimg.com/iu/api/res/1.2/PVfAsIXA.m9sfUrhvw9Q9g--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/04192018/9771.png</image_url>
        <is_undroppable>0</is_undroppable>
        <position_type>B</position_type>
        <eligible_positions>
          <position>2B</position>
          <position>SS</position>
          <position>OF</position>
          <position>Util</position>
        </eligible_positions>
        <has_player_notes>1</has_player_notes>
        <player_notes_last_timestamp>1553377920</player_notes_last_timestamp>
        <selected_position>
          <coverage_type>date</coverage_type>
          <date>2019-03-29</date>
          <position>BN</position>
        </selected_position>
        <is_editable>1</is_editable>
      </player>
      <player>
        <player_key>388.p.9597</player_key>
        <player_id>9597</player_id>
        <name>
          <full>Noah Syndergaard</full>
          <first>Noah</first>
          <last>Syndergaard</last>
          <ascii_first>Noah</ascii_first>
          <ascii_last>Syndergaard</ascii_last>
        </name>
        <editorial_player_key>mlb.p.9597</editorial_player_key>
        <editorial_team_key>mlb.t.21</editorial_team_key>
        <editorial_team_full_name>New York Mets</editorial_team_full_name>
        <editorial_team_abbr>NYM</editorial_team_abbr>
        <uniform_number>34</uniform_number>
        <display_position>SP</display_position>
        <headshot>
          <url>https://s.yimg.com/iu/api/res/1.2/bvBOv.WrvozY6fzm9_8Uqg--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03222019/9597.1.png</url>
          <size>small</size>
        </headshot>
        <image_url>https://s.yimg.com/iu/api/res/1.2/bvBOv.WrvozY6fzm9_8Uqg--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03222019/9597.1.png</image_url>
        <is_undroppable>0</is_undroppable>
        <position_type>P</position_type>
        <eligible_positions>
          <position>SP</position>
          <position>P</position>
        </eligible_positions>
        <selected_position>
          <coverage_type>date</coverage_type>
          <date>2019-03-29</date>
          <position>SP</position>
        </selected_position>
        <is_editable>1</is_editable>
      </player>
      <player>
        <player_key>388.p.10592</player_key>
        <player_id>10592</player_id>
        <name>
          <full>Jack Flaherty</full>
          <first>Jack</first>
          <last>Flaherty</last>
          <ascii_first>Jack</ascii_first>
          <ascii_last>Flaherty</ascii_last>
        </name>
        <editorial_player_key>mlb.p.10592</editorial_player_key>
        <editorial_team_key>mlb.t.24</editorial_team_key>
        <editorial_team_full_name>St. Louis Cardinals</editorial_team_full_name>
        <editorial_team_abbr>StL</editorial_team_abbr>
        <uniform_number>22</uniform_number>
        <display_position>SP</display_position>
        <headshot>
          <url>https://s.yimg.com/iu/api/res/1.2/F1.Ygdsr0l2Hbd5SdfpGwA--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/04042018/10592.png</url>
          <size>small</size>
        </headshot>
        <image_url>https://s.yimg.com/iu/api/res/1.2/F1.Ygdsr0l2Hbd5SdfpGwA--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/04042018/10592.png</image_url>
        <is_undroppable>0</is_undroppable>
        <position_type>P</position_type>
        <eligible_positions>
          <position>SP</position>
          <position>P</position>
        </eligible_positions>
        <has_player_notes>1</has_player_notes>
        <player_notes_last_timestamp>1553458620</player_notes_last_timestamp>
        <selected_position>
          <coverage_type>date</coverage_type>
          <date>2019-03-29</date>
          <position>SP</position>
        </selected_position>
        <starting_status>
          <coverage_type>date</coverage_type>
          <date>2019-03-29</date>
          <is_starting>1</is_starting>
        </starting_status>
        <is_editable>1</is_editable>
      </player>
      <player>
        <player_key>388.p.8641</player_key>
        <player_id>8641</player_id>
        <name>
          <full>Sean Doolittle</full>
          <first>Sean</first>
          <last>Doolittle</last>
          <ascii_first>Sean</ascii_first>
          <ascii_last>Doolittle</ascii_last>
        </name>
        <editorial_player_key>mlb.p.8641</editorial_player_key>
        <editorial_team_key>mlb.t.20</editorial_team_key>
        <editorial_team_full_name>Washington Nationals</editorial_team_full_name>
        <editorial_team_abbr>Was</editorial_team_abbr>
        <uniform_number>63</uniform_number>
        <display_position>RP</display_position>
        <headshot>
          <url>https://s.yimg.com/iu/api/res/1.2/ZnRo0cp0uLOLIJdQczY1ww--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03092018/8641.png</url>
          <size>small</size>
        </headshot>
        <image_url>https://s.yimg.com/iu/api/res/1.2/ZnRo0cp0uLOLIJdQczY1ww--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03092018/8641.png</image_url>
        <is_undroppable>0</is_undroppable>
        <position_type>P</position_type>
        <eligible_positions>
          <position>RP</position>
          <position>P</position>
        </eligible_positions>
        <selected_position>
          <coverage_type>date</coverage_type>
          <date>2019-03-29</date>
          <position>RP</position>
        </selected_position>
        <is_editable>1</is_editable>
      </player>
      <player>
        <player_key>388.p.9616</player_key>
        <player_id>9616</player_id>
        <name>
          <full>Tyler Glasnow</full>
          <first>Tyler</first>
          <last>Glasnow</last>
          <ascii_first>Tyler</ascii_first>
          <ascii_last>Glasnow</ascii_last>
        </name>
        <editorial_player_key>mlb.p.9616</editorial_player_key>
        <editorial_team_key>mlb.t.30</editorial_team_key>
        <editorial_team_full_name>Tampa Bay Rays</editorial_team_full_name>
        <editorial_team_abbr>TB</editorial_team_abbr>
        <uniform_number>20</uniform_number>
        <display_position>SP,RP</display_position>
        <headshot>
          <url>https://s.yimg.com/iu/api/res/1.2/YWbEhBLCfmNAQf4C5dtiig--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03222019/9616.1.png</url>
          <size>small</size>
        </headshot>
        <image_url>https://s.yimg.com/iu/api/res/1.2/YWbEhBLCfmNAQf4C5dtiig--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03222019/9616.1.png</image_url>
        <is_undroppable>0</is_undroppable>
        <position_type>P</position_type>
        <eligible_positions>
          <position>SP</position>
          <position>RP</position>
          <position>P</position>
        </eligible_positions>
        <has_player_notes>1</has_player_notes>
        <player_notes_last_timestamp>1553032740</player_notes_last_timestamp>
        <selected_position>
          <coverage_type>date</coverage_type>
          <date>2019-03-29</date>
          <position>RP</position>
        </selected_position>
        <is_editable>1</is_editable>
      </player>
      <player>
        <player_key>388.p.8175</player_key>
        <player_id>8175</player_id>
        <name>
          <full>David Price</full>
          <first>David</first>
          <last>Price</last>
          <ascii_first>David</ascii_first>
          <ascii_last>Price</ascii_last>
        </name>
        <status>DTD</status>
        <status_full>Day-to-Day</status_full>
        <editorial_player_key>mlb.p.8175</editorial_player_key>
        <editorial_team_key>mlb.t.2</editorial_team_key>
        <editorial_team_full_name>Boston Red Sox</editorial_team_full_name>
        <editorial_team_abbr>Bos</editorial_team_abbr>
        <uniform_number>10</uniform_number>
        <display_position>SP</display_position>
        <headshot>
          <url>https://s.yimg.com/iu/api/res/1.2/WOr.C4SaZj0D62Ek8Squ0A--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03142018/8175.png</url>
          <size>small</size>
        </headshot>
        <image_url>https://s.yimg.com/iu/api/res/1.2/WOr.C4SaZj0D62Ek8Squ0A--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03142018/8175.png</image_url>
        <is_undroppable>0</is_undroppable>
        <position_type>P</position_type>
        <eligible_positions>
          <position>SP</position>
          <position>P</position>
        </eligible_positions>
        <has_player_notes>1</has_player_notes>
        <player_notes_last_timestamp>1553636760</player_notes_last_timestamp>
        <selected_position>
          <coverage_type>date</coverage_type>
          <date>2019-03-29</date>
          <position>P</position>
        </selected_position>
        <is_editable>1</is_editable>
      </player>
      <player>
        <player_key>388.p.10683</player_key>
        <player_id>10683</player_id>
        <name>
          <full>Nick Pivetta</full>
          <first>Nick</first>
          <last>Pivetta</last>
          <ascii_first>Nick</ascii_first>
          <ascii_last>Pivetta</ascii_last>
        </name>
        <editorial_player_key>mlb.p.10683</editorial_player_key>
        <editorial_team_key>mlb.t.22</editorial_team_key>
        <editorial_team_full_name>Philadelphia Phillies</editorial_team_full_name>
        <editorial_team_abbr>Phi</editorial_team_abbr>
        <uniform_number>43</uniform_number>
        <display_position>SP</display_position>
        <headshot>
          <url>https://s.yimg.com/iu/api/res/1.2/iKvayMEYXqtxiwsmt3ZvjQ--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03292018/10683.png</url>
          <size>small</size>
        </headshot>
        <image_url>https://s.yimg.com/iu/api/res/1.2/iKvayMEYXqtxiwsmt3ZvjQ--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03292018/10683.png</image_url>
        <is_undroppable>0</is_undroppable>
        <position_type>P</position_type>
        <eligible_positions>
          <position>SP</position>
          <position>P</position>
        </eligible_positions>
        <has_player_notes>1</has_player_notes>
        <player_notes_last_timestamp>1553111580</player_notes_last_timestamp>
        <selected_position>
          <coverage_type>date</coverage_type>
          <date>2019-03-29</date>
          <position>P</position>
        </selected_position>
        <is_editable>1</is_editable>
      </player>
      <player>
        <player_key>388.p.7578</player_key>
        <player_id>7578</player_id>
        <name>
          <full>Rich Hill</full>
          <first>Rich</first>
          <last>Hill</last>
          <ascii_first>Rich</ascii_first>
          <ascii_last>Hill</ascii_last>
        </name>
        <status>DL10</status>
        <status_full>10-Day Disabled List</status_full>
        <on_disabled_list>1</on_disabled_list>
        <editorial_player_key>mlb.p.7578</editorial_player_key>
        <editorial_team_key>mlb.t.19</editorial_team_key>
        <editorial_team_full_name>Los Angeles Dodgers</editorial_team_full_name>
        <editorial_team_abbr>LAD</editorial_team_abbr>
        <uniform_number>44</uniform_number>
        <display_position>SP</display_position>
        <headshot>
          <url>https://s.yimg.com/iu/api/res/1.2/Adolm4ZvoSfxYzu2XXPACw--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/04192018/7578.png</url>
          <size>small</size>
        </headshot>
        <image_url>https://s.yimg.com/iu/api/res/1.2/Adolm4ZvoSfxYzu2XXPACw--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/04192018/7578.png</image_url>
        <is_undroppable>0</is_undroppable>
        <position_type>P</position_type>
        <eligible_positions>
          <position>SP</position>
          <position>P</position>
          <position>DL</position>
        </eligible_positions>
        <has_player_notes>1</has_player_notes>
        <player_notes_last_timestamp>1553796720</player_notes_last_timestamp>
        <selected_position>
          <coverage_type>date</coverage_type>
          <date>2019-03-29</date>
          <position>P</position>
        </selected_position>
        <is_editable>1</is_editable>
      </player>
      <player>
        <player_key>388.p.10575</player_key>
        <player_id>10575</player_id>
        <name>
          <full>Chris Paddack</full>
          <first>Chris</first>
          <last>Paddack</last>
          <ascii_first>Chris</ascii_first>
          <ascii_last>Paddack</ascii_last>
        </name>
        <editorial_player_key>mlb.p.10575</editorial_player_key>
        <editorial_team_key>mlb.t.25</editorial_team_key>
        <editorial_team_full_name>San Diego Padres</editorial_team_full_name>
        <editorial_team_abbr>SD</editorial_team_abbr>
        <uniform_number>59</uniform_number>
        <display_position>SP</display_position>
        <headshot>
          <url>https://s.yimg.com/iu/api/res/1.2/jJkLq8Jbepv7Fu1O_sl6Kw--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03222019/10575.1.png</url>
          <size>small</size>
        </headshot>
        <image_url>https://s.yimg.com/iu/api/res/1.2/jJkLq8Jbepv7Fu1O_sl6Kw--~B/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/03222019/10575.1.png</image_url>
        <is_undroppable>0</is_undroppable>
        <position_type>P</position_type>
        <eligible_positions>
          <position>SP</position>
          <position>P</position>
        </eligible_positions>
        <has_player_notes>1</has_player_notes>
        <player_notes_last_timestamp>1553573220</player_notes_last_timestamp>
        <selected_position>
          <coverage_type>date</coverage_type>
          <date>2019-03-29</date>
          <position>P</position>
        </selected_position>
        <is_editable>1</is_editable>
      </player>
    </players>"
  end

  let(:roster_response) do
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<fantasy_content xml:lang=\"en-US\" yahoo:uri=\"http://fantasysports.yahooapis.com/fantasy/v2/team/388.l.161732.t.11/roster/players\" time=\"149.62601661682ms\" copyright=\"Data provided by Yahoo! and STATS, LLC\" refresh_rate=\"60\" xmlns:yahoo=\"http://www.yahooapis.com/v1/base.rng\" xmlns=\"http://fantasysports.yahooapis.com/fantasy/v2/base.rng\">
  <team>
    <team_key>388.l.161732.t.11</team_key>
    <team_id>11</team_id>
    <name>Andrew's Team</name>
    <is_owned_by_current_login>1</is_owned_by_current_login>
    <url>https://baseball.fantasysports.yahoo.com/b1/161732/11</url>
    <team_logos>
      <team_logo>
        <size>large</size>
        <url>https://s.yimg.com/cv/apiv2/default/mlb/mlb_12_a.png</url>
      </team_logo>
    </team_logos>
    <waiver_priority>10</waiver_priority>
    <number_of_moves>0</number_of_moves>
    <number_of_trades>0</number_of_trades>
    <roster_adds>
      <coverage_type>week</coverage_type>
      <coverage_value>1</coverage_value>
      <value>0</value>
    </roster_adds>
    <league_scoring_type>roto</league_scoring_type>
    <has_draft_grade>0</has_draft_grade>
    <auction_budget_total>260</auction_budget_total>
    <auction_budget_spent>260</auction_budget_spent>
    <managers>
      <manager>
        <manager_id>11</manager_id>
        <nickname>Andrew</nickname>
        <guid>OFWR6UB5YDFVEZDE3YL3B7IGV4</guid>
        <is_current_login>1</is_current_login>
        <email>apetit29@yahoo.com</email>
        <image_url>https://ct.yimg.com/cy/1768/39361574426_98028a_64sq.jpg</image_url>
      </manager>
    </managers>
    <roster>
    #{roster}
    </roster>
  </team>
</fantasy_content>
<!-- fanos146.sports.bf1.yahoo.com Fri Mar 29 18:59:31 UTC 2019 -->"
  end
end
