default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  yahoo_client_key: <%= ENV["YAHOO_CLIENT_KEY"] %>
  yahoo_client_secret: <%= ENV["YAHOO_CLIENT_SECRET"] %> 
  seat_geek_client_id: <%= ENV["SEAT_GEEK_CLIENT_ID"] %>
  email: <%= ENV["EMAIL"] %>
  gmail_username: <%= ENV["GMAIL_USERNAME"] %>
  gmail_password: <%= ENV["GMAIL_PASSWORD"] %>

production:
  <<: *default

development:
  <<: *default

test:
  secret_key_base: 3b403d2260319160e445c76a5ef1982b90dbed011afb37145071af3abcca285a4f803519cc94eddbe9aa3768445ff1a8ac009ec68a572f73685fedbac33d1fb1
  yahoo_client_key: = none
  yahoo_client_secret: = none
  seat_geek_client_id: = none
  email: test@test.com
  gmail_username: test
  gmail_password: pass
